### ISSUE TITLE
GEOSgcm MAPL3 Run Failure with GNU (2023-Jul-28)

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MAPL#2262]
Runs of GEOSgcm are failing with GNU as of last night:

```
 Logical Resource Parameter: FIRE_DANGER:F, (default value)
At line 5114 of file /discover/nobackup/mathomp4/SystemTests/builds/AGCM_GNUMAPL3/CURRENT/GEOSgcm/src/Shared/@MAPL/generic/MAPL_Generic.F90
Fortran runtime error: Pointer argument 'meta_child' is not associated

```

it seems to happen after `FIRE_DANGER` is printed which points to somewhere in surface.
```
#0  0x2b53f9e96bd1 in __mapl_genericmod_MOD_mapl_terminateimportallbut
        at /discover/nobackup/mathomp4/SystemTests/builds/AGCM_GNUMAPL3/CURRENT/GEOSgcm/src/Shared/@MAPL/generic/MAPL_Generic.F90:5114
#1  0x42b3969 in __geos_surfacegridcompmod_MOD_setservices
        at /discover/nobackup/mathomp4/SystemTests/builds/AGCM_GNUMAPL3/CURRENT/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_Surf
aceGridComp.F90:3313
```

This is a new-ish bit of code from @zhaobin74:
```fortran
! call MAPL_TerminateImport    ( GC, CHILD = OCEAN,   RC=STATUS  )
  call MAPL_TerminateImport    ( GC, SHORT_NAMES=['SURFSTATE'],    &
                                 CHILD_IDS=[OCEAN],  RC=STATUS  )
```
where the old code is the comment and the new code is the uncommented.

But, MAPL2 is just fine and happy with this new code!

**Comment by mathomp4** [comment]
Update. I can "solve" the GNU issue by doing:
```fortran
    INTEGER                                 :: DO_CICE_THERMO
...
    call MAPL_GetResource ( MAPL, DO_CICE_THERMO,     Label="USE_CICE_Thermo:" ,    DEFAULT=0, _RC)
    if (DO_CICE_THERMO == 2) then
       call MAPL_TerminateImport    ( GC, SHORT_NAMES=['SURFSTATE'],    &
                                      CHILD_IDS=[OCEAN],  RC=STATUS  )
       VERIFY_(STATUS)
    else
       call MAPL_TerminateImport    ( GC, CHILD = OCEAN,   RC=STATUS  )
       VERIFY_(STATUS)
    endif
```
though we'd need to know from @zhaobin74 if that is correct. But even this does not help #2263  😦

**Comment by zhaobin74** [comment]
@mathomp4 , I have no objection to this change. Indeed, Terminate SURFSTATE is only needed by CICE6 coupling, i.e. DO_CICE_THERMO == 2. I don't  know why MAPL_v2 is ok with it.

**Comment by mathomp4** [comment]
Close in favor of #2264
