### ISSUE TITLE
MAPL standalone build appears to be broken

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/MAPL#865]
I checked out develop and tried to build MAPL on Discover.  So checkout the MAPL repo, go there checkout develop, then mepo clone, the source g5_modules, then build.
Note I've also tried this with main and v2.7.0
I'm getting a slew of errors when running the cmake command:
```
-- Detecting C compile features
-- Detecting C compile features - done
Traceback (most recent call last):
  File "/discover/swdev/gmao_SIteam/mepo/mepo", line 17, in <module>
    main()
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/main.py", line 6, in main
    command.run(args)
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/command/command.py", line 11, in run
    cmd_module.run(args)
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/command/init/init.py", line 17, in run
    allcomps = MepoState.initialize(args.config,style)
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/state/state.py", line 58, in initialize
    raise StateAlreadyInitializedError('mepo state already exists')
state.exceptions.StateAlreadyInitializedError: mepo state already exists
fatal: destination path './@ESMA_env' already exists and is not an empty directory.

Traceback (most recent call last):
  File "/discover/swdev/gmao_SIteam/mepo/mepo", line 17, in <module>
    main()
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/main.py", line 6, in main
    command.run(args)
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/command/command.py", line 11, in run
    cmd_module.run(args)
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/command/clone/clone.py", line 68, in run
    git.clone(version,recurse)
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/repository/git.py", line 45, in clone
    shellcmd.run(cmd.split())
  File "/gpfsm/dswdev/gmao_SIteam/mepo/mepo.d/utilities/shellcmd.py", line 15, in run
    result.check_returncode()
  File "/usr/local/other/python/GEOSpyD/4.9.2_py3.9/2021-05-05/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['git', 'clone', '--branch', 'v3.2.1', '--quiet', 'git@github.com:GEOS-ESM/ESMA_env.git', './@ESMA_env']' returned non-zero exit status 128.
CMake Error at CMakeLists.txt:37 (include):
  include could not find load file:

    esma


CMake Error at CMakeLists.txt:45 (find_package):
  By not providing "FindFLAP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "FLAP", but
  CMake did not find one.

  Could not find a package configuration file provided by "FLAP" with any of
  the following names:

    FLAPConfig.cmake
    flap-config.cmake

  Add the installation prefix of "FLAP" to CMAKE_PREFIX_PATH or set
  "FLAP_DIR" to a directory containing one of the above files.  If "FLAP"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/bmauer/swdev/models/mapl_fix_regrid/mapl_bare/MAPL/build/CMakeFiles/CMakeOutput.log".
```

**Comment by mathomp4** [comment]
Okay. I "fixed" this by fixing `mepo`. But I am also going to make a PR to fix this without the need to fix `mepo`.

**Comment by bena-nasa** [comment]
Seems fixed
